# Generated by Django 2.2 on 2022-10-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='proposal_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='proposal_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
