# Generated by Django 4.1.2 on 2022-11-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_profile_gender_identity_profile_sexual_orientation"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="age_preference",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
