# Generated by Django 4.1.2 on 2022-11-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_profile_age_preference"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="age_preference",
            new_name="age_preference_max",
        ),
        migrations.AddField(
            model_name="profile",
            name="age_preference_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="gender_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Woman", "Woman"),
                    ("Man", "Man"),
                    ("Transgender", "Transgender"),
                    ("Non-binary", "Non-binaary"),
                ],
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="orientation_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Lesbian", "Lesbian"),
                    ("Gay", "Gay"),
                    ("Bisexual", "Bisexual"),
                    ("Queer", "Queer"),
                    ("Asexual", "Asexual"),
                    ("Straight", "Straight"),
                    ("Other", "Other"),
                ],
                max_length=15,
            ),
        ),
    ]
