# Generated by Django 4.1.2 on 2022-11-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_remove_profile_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
