# Generated by Django 4.1.2 on 2022-11-07 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_auto_20221106_1419"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="users_like",
        ),
        migrations.AddField(
            model_name="profile",
            name="hides",
            field=models.ManyToManyField(
                blank=True, related_name="hidden_by", to="account.profile"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_by", to="account.profile"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(
                blank=True, default=datetime.date(2022, 11, 7), null=True
            ),
        ),
    ]
