# Generated by Django 4.1.2 on 2022-11-11 19:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_profile_matches_alter_profile_date_of_birth"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DBA", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(
                blank=True, default=datetime.date(2022, 11, 11), null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender_identity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Woman", "Woman"),
                    ("Man", "Man"),
                    ("Transgender", "Transgender"),
                    ("Non-binary", "Non-binary"),
                ],
                default="N/A",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Woman", "Woman"),
                    ("Man", "Man"),
                    ("Transgender", "Transgender"),
                    ("Non-binary", "Non-binary"),
                ],
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="location_drawdown",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="account.location",
            ),
        ),
    ]
