# Generated by Django 4.1.2 on 2022-11-11 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_location_boro_location_building_location_cuisine_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="location_drawdown",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
