# Generated by Django 4.1.2 on 2022-11-14 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0019_alter_location_boro_alter_location_building_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="proposal_location",
        ),
    ]
