# Generated by Django 4.1.2 on 2022-11-16 17:12

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0022_alter_profile_location_dropdown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="location_dropdown",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                blank=True,
                chained_field="cusine",
                chained_model_field="cusine",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.newlocation",
            ),
        ),
    ]
