# Generated by Django 4.1.2 on 2022-11-16 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0024_alter_profile_location_dropdown"),
    ]

    operations = [
        migrations.CreateModel(
            name="Boro",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("boro", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="profile",
            name="location_dropdown",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="account.newlocation",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="boro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="account.boro",
            ),
        ),
        migrations.AlterField(
            model_name="newlocation",
            name="BORO",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="account.boro",
            ),
        ),
    ]
