# Generated by Django 4.1.2 on 2022-11-20 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0025_boro_alter_profile_location_dropdown_profile_boro_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="location_drawdown",
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(
                blank=True, default=datetime.date(2022, 11, 20), null=True
            ),
        ),
    ]
