# Generated by Django 4.1.2 on 2022-11-21 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0026_remove_profile_location_drawdown_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="declines",
            field=models.ManyToManyField(
                blank=True, related_name="declined_by", to="account.profile"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(
                blank=True, default=datetime.date(2022, 11, 21), null=True
            ),
        ),
    ]
