# Generated by Django 2.2 on 2022-11-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20221124_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='proposal_datetime',
        ),
        migrations.AddField(
            model_name='profile',
            name='proposal_date_new',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='proposal_time_new',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
