# Generated by Django 2.2 on 2022-11-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_auto_20221124_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='proposal_datetime_local',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
