# Generated by Django 2.2 on 2022-11-27 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_profile_proposal_datetime_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='proposal_date_new',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='proposal_time',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='proposal_time_new',
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date(2022, 11, 27), null=True),
        ),
    ]
