# Generated by Django 2.2 on 2022-11-28 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_auto_20221127_1152'),
        ('account', '0028_auto_20221123_1747'),
    ]

    operations = [
    ]
