# Generated by Django 2.2 on 2022-11-30 20:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20221128_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age_preference_max',
            field=models.PositiveIntegerField(blank=True, default=20, null=True, validators=[django.core.validators.MinValueValidator(19), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age_preference_min',
            field=models.PositiveIntegerField(blank=True, default=19, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date(2022, 11, 30), null=True),
        ),
    ]
