# Generated by Django 2.2 on 2022-12-01 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_auto_20221130_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='orientation_preference',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sexual_orientation',
        ),
    ]
