# Generated by Django 2.2 on 2022-12-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_auto_20221130_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender_preference',
            field=models.CharField(blank=True, choices=[('Woman', 'Woman'), ('Man', 'Man'), ('Both', 'Both'), ('Transgender', 'Transgender'), ('Non-binary', 'Non-binary')], max_length=15),
        ),
    ]
