# Generated by Django 2.2 on 2022-12-01 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_auto_20221130_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location_dropdown',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.newLocation'),
        ),
    ]
