# Generated by Django 2.2 on 2022-12-05 15:34

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0038_auto_20221130_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age_preference_max',
            field=models.PositiveIntegerField(blank=True, default=20, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date(2022, 12, 5), null=True),
        ),
        migrations.CreateModel(
            name='Match_Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField(blank=True, null=True)),
                ('date_happened', models.CharField(blank=True, choices=[('Yes', 'We both showed up'), ('No1', 'My match wasn’t there'), ('No2', 'I didn’t go')], max_length=50, null=True)),
                ('inappropriate_behavior', models.CharField(blank=True, max_length=50, null=True)),
                ('match_rating', models.IntegerField(blank=True, null=True)),
                ('match_comments', models.CharField(blank=True, max_length=500, null=True)),
                ('feedback_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_by_user', to=settings.AUTH_USER_MODEL)),
                ('match_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.newLocation')),
                ('matched_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
