# Generated by Django 2.2 on 2022-12-05 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_auto_20221205_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location_dropdown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.newLocation'),
        ),
    ]
