# Generated by Django 4.1.2 on 2022-12-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0040_auto_20221205_1543"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="feedback_submitted",
            field=models.BooleanField(default=False),
        ),
    ]
