# Generated by Django 2.2 on 2022-12-13 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_auto_20221210_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='warning_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date(2022, 12, 13), null=True),
        ),
    ]
