# Generated by Django 4.1.2 on 2022-12-15 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0046_auto_20221214_1226"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(
                blank=True, default=datetime.date(2022, 12, 15), null=True
            ),
        ),
    ]
