# Generated by Django 3.2.16 on 2022-12-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_auto_20221217_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='attendees_one',
            field=models.CharField(default='nobody', max_length=250),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='attendees_two',
            field=models.CharField(default='nobody', max_length=250),
        ),
    ]
