# Generated by Django 3.2.16 on 2022-12-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_auto_20221218_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chatroom_slug',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
