# Generated by Django 3.2.16 on 2022-12-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_profile_chatroom_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile',
        ),
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ManyToManyField(to='account.Profile'),
        ),
    ]
