# Generated by Django 4.1.2 on 2022-12-18 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0047_alter_profile_date_of_birth"),
        ("account", "0056_auto_20221218_1354"),
    ]

    operations = []
