# Generated by Django 2.2 on 2022-12-18 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0056_auto_20221218_1354'),
        ('account', '0047_alter_profile_date_of_birth'),
    ]

    operations = [
    ]
