# Generated by Django 4.1.2 on 2022-12-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0057_merge_20221218_2156"),
        ("account", "0057_merge_20221218_2201"),
    ]

    operations = []
