# Generated by Django 4.1.2 on 2022-12-19 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0058_merge_20221218_2235"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(
                blank=True, default=datetime.date(2022, 12, 19), null=True
            ),
        ),
    ]
