# Generated by Django 4.1.2 on 2022-11-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_auto_20221030_1946"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="gender_identity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Woman", "Woman"),
                    ("Man", "Man"),
                    ("Transgender", "Transgender"),
                    ("Non-binary", "Non-binaary"),
                ],
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="sexual_orientation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Lesbian", "Lesbian"),
                    ("Gay", "Gay"),
                    ("Bisexual", "Bisexual"),
                    ("Queer", "Queer"),
                    ("Asexual", "Asexual"),
                    ("Straight", "Straight"),
                    ("Other", "Other"),
                ],
                max_length=15,
            ),
        ),
    ]
