# Generated by Django 4.1.3 on 2022-11-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_profile_age_profile_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='hides',
            field=models.ManyToManyField(blank=True, related_name='hidden_by', to='account.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='account.profile'),
        ),
    ]
