# Generated by Django 4.1.3 on 2022-11-11 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_profile_matches_alter_profile_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(
                blank=True, default=datetime.date(2022, 11, 11), null=True
            ),
        ),
    ]
