# Generated by Django 4.1.2 on 2022-11-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_location_alter_profile_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="BORO",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="BUILDING",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="CUISINE",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="LATITUDE",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="LONGITUDE",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="PHONE",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="STREET",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="ZIPCODE",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="DBA",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
