# Generated by Django 4.1.2 on 2022-11-11 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0017_remove_profile_location_drawdown_delete_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DBA", models.CharField(max_length=100, null=True)),
                ("BORO", models.CharField(max_length=100, null=True)),
                ("BUILDING", models.CharField(max_length=20, null=True)),
                ("STREET", models.CharField(max_length=40, null=True)),
                ("ZIPCODE", models.FloatField(null=True)),
                ("PHONE", models.CharField(max_length=12, null=True)),
                ("CUISINE", models.CharField(max_length=20, null=True)),
                ("LATITUDE", models.FloatField(null=True)),
                ("LONGITUDE", models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="location_drawdown",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="account.location",
            ),
        ),
    ]
