# Generated by Django 4.1.2 on 2022-11-16 17:09

from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0021_cusine_alter_profile_date_of_birth_newlocation_and_more"),
    ]
