# Generated by Django 4.1.2 on 2022-11-16 17:15

from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0023_alter_profile_location_dropdown"),
    ]
