# Generated by Django 4.1.2 on 2022-11-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_place_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="place",
        ),
    ]
