# Generated by Django 3.1 on 2022-10-31 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('date', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dummyprofile',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='dummyprofile',
            name='likeability',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
